server:
  port: 80

eureka:
  client:
    register-with-eureka: false  # 此客户端不进行注册
    service-url:
      defaultZone: http://eureka-server-7001.com:7001/eureka/,http://eureka-server-7002.com:7002/eureka/,http://eureka-server-7003.com:7003/eureka/

## 自定义参数
dept:
  url:
    preffix: http://PROVIDER-DEPT  # 使用负载均衡组件后，可以使用【服务名称】代替具体的服务提供者所在的 URI 地址
    # preffix: "http://localhost:8001"
